package com.gfan.report.frame.module;

import java.util.Date;

public class CorpPartnerUser {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column corp_partner_user.id
     *
     * @ibatorgenerated Tue May 12 18:31:37 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column corp_partner_user.user_id
     *
     * @ibatorgenerated Tue May 12 18:31:37 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column corp_partner_user.partner_id
     *
     * @ibatorgenerated Tue May 12 18:31:37 CST 2015
     */
    private Integer partnerId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column corp_partner_user.phone_no
     *
     * @ibatorgenerated Tue May 12 18:31:37 CST 2015
     */
    private String phoneNo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column corp_partner_user.email
     *
     * @ibatorgenerated Tue May 12 18:31:37 CST 2015
     */
    private String email;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column corp_partner_user.name
     *
     * @ibatorgenerated Tue May 12 18:31:37 CST 2015
     */
    private String name;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column corp_partner_user.status
     *
     * @ibatorgenerated Tue May 12 18:31:37 CST 2015
     */
    private Byte status;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column corp_partner_user.channel_id
     *
     * @ibatorgenerated Tue May 12 18:31:37 CST 2015
     */
    private Integer channelId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column corp_partner_user.admin
     *
     * @ibatorgenerated Tue May 12 18:31:37 CST 2015
     */
    private Byte admin;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column corp_partner_user.tag_id
     *
     * @ibatorgenerated Tue May 12 18:31:37 CST 2015
     */
    private Integer tagId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column corp_partner_user.managed
     *
     * @ibatorgenerated Tue May 12 18:31:37 CST 2015
     */
    private Byte managed;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column corp_partner_user.create_time
     *
     * @ibatorgenerated Tue May 12 18:31:37 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column corp_partner_user.modify_time
     *
     * @ibatorgenerated Tue May 12 18:31:37 CST 2015
     */
    private Date modifyTime;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column corp_partner_user.id
     *
     * @return the value of corp_partner_user.id
     *
     * @ibatorgenerated Tue May 12 18:31:37 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column corp_partner_user.id
     *
     * @param id the value for corp_partner_user.id
     *
     * @ibatorgenerated Tue May 12 18:31:37 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column corp_partner_user.user_id
     *
     * @return the value of corp_partner_user.user_id
     *
     * @ibatorgenerated Tue May 12 18:31:37 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column corp_partner_user.user_id
     *
     * @param userId the value for corp_partner_user.user_id
     *
     * @ibatorgenerated Tue May 12 18:31:37 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column corp_partner_user.partner_id
     *
     * @return the value of corp_partner_user.partner_id
     *
     * @ibatorgenerated Tue May 12 18:31:37 CST 2015
     */
    public Integer getPartnerId() {
        return partnerId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column corp_partner_user.partner_id
     *
     * @param partnerId the value for corp_partner_user.partner_id
     *
     * @ibatorgenerated Tue May 12 18:31:37 CST 2015
     */
    public void setPartnerId(Integer partnerId) {
        this.partnerId = partnerId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column corp_partner_user.phone_no
     *
     * @return the value of corp_partner_user.phone_no
     *
     * @ibatorgenerated Tue May 12 18:31:37 CST 2015
     */
    public String getPhoneNo() {
        return phoneNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column corp_partner_user.phone_no
     *
     * @param phoneNo the value for corp_partner_user.phone_no
     *
     * @ibatorgenerated Tue May 12 18:31:37 CST 2015
     */
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column corp_partner_user.email
     *
     * @return the value of corp_partner_user.email
     *
     * @ibatorgenerated Tue May 12 18:31:37 CST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column corp_partner_user.email
     *
     * @param email the value for corp_partner_user.email
     *
     * @ibatorgenerated Tue May 12 18:31:37 CST 2015
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column corp_partner_user.name
     *
     * @return the value of corp_partner_user.name
     *
     * @ibatorgenerated Tue May 12 18:31:37 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column corp_partner_user.name
     *
     * @param name the value for corp_partner_user.name
     *
     * @ibatorgenerated Tue May 12 18:31:37 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column corp_partner_user.status
     *
     * @return the value of corp_partner_user.status
     *
     * @ibatorgenerated Tue May 12 18:31:37 CST 2015
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column corp_partner_user.status
     *
     * @param status the value for corp_partner_user.status
     *
     * @ibatorgenerated Tue May 12 18:31:37 CST 2015
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column corp_partner_user.channel_id
     *
     * @return the value of corp_partner_user.channel_id
     *
     * @ibatorgenerated Tue May 12 18:31:37 CST 2015
     */
    public Integer getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column corp_partner_user.channel_id
     *
     * @param channelId the value for corp_partner_user.channel_id
     *
     * @ibatorgenerated Tue May 12 18:31:37 CST 2015
     */
    public void setChannelId(Integer channelId) {
        this.channelId = channelId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column corp_partner_user.admin
     *
     * @return the value of corp_partner_user.admin
     *
     * @ibatorgenerated Tue May 12 18:31:37 CST 2015
     */
    public Byte getAdmin() {
        return admin;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column corp_partner_user.admin
     *
     * @param admin the value for corp_partner_user.admin
     *
     * @ibatorgenerated Tue May 12 18:31:37 CST 2015
     */
    public void setAdmin(Byte admin) {
        this.admin = admin;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column corp_partner_user.tag_id
     *
     * @return the value of corp_partner_user.tag_id
     *
     * @ibatorgenerated Tue May 12 18:31:37 CST 2015
     */
    public Integer getTagId() {
        return tagId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column corp_partner_user.tag_id
     *
     * @param tagId the value for corp_partner_user.tag_id
     *
     * @ibatorgenerated Tue May 12 18:31:37 CST 2015
     */
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column corp_partner_user.managed
     *
     * @return the value of corp_partner_user.managed
     *
     * @ibatorgenerated Tue May 12 18:31:37 CST 2015
     */
    public Byte getManaged() {
        return managed;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column corp_partner_user.managed
     *
     * @param managed the value for corp_partner_user.managed
     *
     * @ibatorgenerated Tue May 12 18:31:37 CST 2015
     */
    public void setManaged(Byte managed) {
        this.managed = managed;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column corp_partner_user.create_time
     *
     * @return the value of corp_partner_user.create_time
     *
     * @ibatorgenerated Tue May 12 18:31:37 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column corp_partner_user.create_time
     *
     * @param createTime the value for corp_partner_user.create_time
     *
     * @ibatorgenerated Tue May 12 18:31:37 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column corp_partner_user.modify_time
     *
     * @return the value of corp_partner_user.modify_time
     *
     * @ibatorgenerated Tue May 12 18:31:37 CST 2015
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column corp_partner_user.modify_time
     *
     * @param modifyTime the value for corp_partner_user.modify_time
     *
     * @ibatorgenerated Tue May 12 18:31:37 CST 2015
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}