package com.gfan.report.frame.module;

public class PMemberRole {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column p_member_role.id
     *
     * @ibatorgenerated Wed Apr 29 16:17:26 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column p_member_role.user_id
     *
     * @ibatorgenerated Wed Apr 29 16:17:26 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column p_member_role.role_id
     *
     * @ibatorgenerated Wed Apr 29 16:17:26 CST 2015
     */
    private Integer roleId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column p_member_role.id
     *
     * @return the value of p_member_role.id
     *
     * @ibatorgenerated Wed Apr 29 16:17:26 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column p_member_role.id
     *
     * @param id the value for p_member_role.id
     *
     * @ibatorgenerated Wed Apr 29 16:17:26 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column p_member_role.user_id
     *
     * @return the value of p_member_role.user_id
     *
     * @ibatorgenerated Wed Apr 29 16:17:26 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column p_member_role.user_id
     *
     * @param userId the value for p_member_role.user_id
     *
     * @ibatorgenerated Wed Apr 29 16:17:26 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column p_member_role.role_id
     *
     * @return the value of p_member_role.role_id
     *
     * @ibatorgenerated Wed Apr 29 16:17:26 CST 2015
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column p_member_role.role_id
     *
     * @param roleId the value for p_member_role.role_id
     *
     * @ibatorgenerated Wed Apr 29 16:17:26 CST 2015
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}