package com.gfan.report.frame.module;

import java.sql.Timestamp;
import java.util.Date;

public class RepQuery {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column rep_query.REPORT_NAME
	 * @ibatorgenerated  Thu Dec 04 17:40:07 CST 2014
	 */
	private String reportName;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column rep_query.ID
	 * @ibatorgenerated  Thu Dec 04 17:40:07 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column rep_query.REPORT_SQL
	 * @ibatorgenerated  Thu Dec 04 17:40:07 CST 2014
	 */
	private String reportSql;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column rep_query.COUNT_SQL
	 * @ibatorgenerated  Thu Dec 04 17:40:07 CST 2014
	 */
	private String countSql;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column rep_query.REPLACE_FIELD
	 * @ibatorgenerated  Thu Dec 04 17:40:07 CST 2014
	 */
	private String replaceField;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column rep_query.COUNT_FIELD
	 * @ibatorgenerated  Thu Dec 04 17:40:07 CST 2014
	 */
	private String countField;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column rep_query.QUERY_FIELD
	 * @ibatorgenerated  Thu Dec 04 17:40:07 CST 2014
	 */
	private String queryField;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column rep_query.REPORT_RESULT
	 * @ibatorgenerated  Thu Dec 04 17:40:07 CST 2014
	 */
	private String reportResult;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column rep_query.REPORT_TITLE
	 * @ibatorgenerated  Thu Dec 04 17:40:07 CST 2014
	 */
	private String reportTitle;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column rep_query.REPORT_USED
	 * @ibatorgenerated  Thu Dec 04 17:40:07 CST 2014
	 */
	private Short reportUsed;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column rep_query.REPORT_DB
	 * @ibatorgenerated  Thu Dec 04 17:40:07 CST 2014
	 */
	private String reportDb;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column rep_query.INSERT_TIME
	 * @ibatorgenerated  Thu Dec 04 17:40:07 CST 2014
	 */
	private Date insertTime;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column rep_query.REPORT_NAME
	 * @return  the value of rep_query.REPORT_NAME
	 * @ibatorgenerated  Thu Dec 04 17:40:07 CST 2014
	 */
	public String getReportName() {
		return reportName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column rep_query.REPORT_NAME
	 * @param reportName  the value for rep_query.REPORT_NAME
	 * @ibatorgenerated  Thu Dec 04 17:40:07 CST 2014
	 */
	public void setReportName(String reportName) {
		this.reportName = reportName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column rep_query.ID
	 * @return  the value of rep_query.ID
	 * @ibatorgenerated  Thu Dec 04 17:40:07 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column rep_query.ID
	 * @param id  the value for rep_query.ID
	 * @ibatorgenerated  Thu Dec 04 17:40:07 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column rep_query.REPORT_SQL
	 * @return  the value of rep_query.REPORT_SQL
	 * @ibatorgenerated  Thu Dec 04 17:40:07 CST 2014
	 */
	public String getReportSql() {
		return reportSql;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column rep_query.REPORT_SQL
	 * @param reportSql  the value for rep_query.REPORT_SQL
	 * @ibatorgenerated  Thu Dec 04 17:40:07 CST 2014
	 */
	public void setReportSql(String reportSql) {
		this.reportSql = reportSql;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column rep_query.COUNT_SQL
	 * @return  the value of rep_query.COUNT_SQL
	 * @ibatorgenerated  Thu Dec 04 17:40:07 CST 2014
	 */
	public String getCountSql() {
		return countSql;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column rep_query.COUNT_SQL
	 * @param countSql  the value for rep_query.COUNT_SQL
	 * @ibatorgenerated  Thu Dec 04 17:40:07 CST 2014
	 */
	public void setCountSql(String countSql) {
		this.countSql = countSql;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column rep_query.REPLACE_FIELD
	 * @return  the value of rep_query.REPLACE_FIELD
	 * @ibatorgenerated  Thu Dec 04 17:40:07 CST 2014
	 */
	public String getReplaceField() {
		return replaceField;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column rep_query.REPLACE_FIELD
	 * @param replaceField  the value for rep_query.REPLACE_FIELD
	 * @ibatorgenerated  Thu Dec 04 17:40:07 CST 2014
	 */
	public void setReplaceField(String replaceField) {
		this.replaceField = replaceField;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column rep_query.COUNT_FIELD
	 * @return  the value of rep_query.COUNT_FIELD
	 * @ibatorgenerated  Thu Dec 04 17:40:07 CST 2014
	 */
	public String getCountField() {
		return countField;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column rep_query.COUNT_FIELD
	 * @param countField  the value for rep_query.COUNT_FIELD
	 * @ibatorgenerated  Thu Dec 04 17:40:07 CST 2014
	 */
	public void setCountField(String countField) {
		this.countField = countField;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column rep_query.QUERY_FIELD
	 * @return  the value of rep_query.QUERY_FIELD
	 * @ibatorgenerated  Thu Dec 04 17:40:07 CST 2014
	 */
	public String getQueryField() {
		return queryField;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column rep_query.QUERY_FIELD
	 * @param queryField  the value for rep_query.QUERY_FIELD
	 * @ibatorgenerated  Thu Dec 04 17:40:07 CST 2014
	 */
	public void setQueryField(String queryField) {
		this.queryField = queryField;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column rep_query.REPORT_RESULT
	 * @return  the value of rep_query.REPORT_RESULT
	 * @ibatorgenerated  Thu Dec 04 17:40:07 CST 2014
	 */
	public String getReportResult() {
		return reportResult;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column rep_query.REPORT_RESULT
	 * @param reportResult  the value for rep_query.REPORT_RESULT
	 * @ibatorgenerated  Thu Dec 04 17:40:07 CST 2014
	 */
	public void setReportResult(String reportResult) {
		this.reportResult = reportResult;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column rep_query.REPORT_TITLE
	 * @return  the value of rep_query.REPORT_TITLE
	 * @ibatorgenerated  Thu Dec 04 17:40:07 CST 2014
	 */
	public String getReportTitle() {
		return reportTitle;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column rep_query.REPORT_TITLE
	 * @param reportTitle  the value for rep_query.REPORT_TITLE
	 * @ibatorgenerated  Thu Dec 04 17:40:07 CST 2014
	 */
	public void setReportTitle(String reportTitle) {
		this.reportTitle = reportTitle;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column rep_query.REPORT_USED
	 * @return  the value of rep_query.REPORT_USED
	 * @ibatorgenerated  Thu Dec 04 17:40:07 CST 2014
	 */
	public Short getReportUsed() {
		return reportUsed;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column rep_query.REPORT_USED
	 * @param reportUsed  the value for rep_query.REPORT_USED
	 * @ibatorgenerated  Thu Dec 04 17:40:07 CST 2014
	 */
	public void setReportUsed(Short reportUsed) {
		this.reportUsed = reportUsed;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column rep_query.REPORT_DB
	 * @return  the value of rep_query.REPORT_DB
	 * @ibatorgenerated  Thu Dec 04 17:40:07 CST 2014
	 */
	public String getReportDb() {
		return reportDb;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column rep_query.REPORT_DB
	 * @param reportDb  the value for rep_query.REPORT_DB
	 * @ibatorgenerated  Thu Dec 04 17:40:07 CST 2014
	 */
	public void setReportDb(String reportDb) {
		this.reportDb = reportDb;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column rep_query.INSERT_TIME
	 * @return  the value of rep_query.INSERT_TIME
	 * @ibatorgenerated  Thu Dec 04 17:40:07 CST 2014
	 */
	public Date getInsertTime() {
		return insertTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column rep_query.INSERT_TIME
	 * @param insertTime  the value for rep_query.INSERT_TIME
	 * @ibatorgenerated  Thu Dec 04 17:40:07 CST 2014
	 */
	public void setInsertTime(Date insertTime) {
		this.insertTime = insertTime;
	}
	
}
