package com.gfan.report.frame.module;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class UiFwModule implements Serializable {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column UI_FW_MODULE.ID
     *
     * @ibatorgenerated Thu Sep 25 15:11:52 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column UI_FW_MODULE.NAME
     *
     * @ibatorgenerated Thu Sep 25 15:11:52 CST 2014
     */
    private String name;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column UI_FW_MODULE.ACTION_URL
     *
     * @ibatorgenerated Thu Sep 25 15:11:52 CST 2014
     */
    private String actionUrl;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column UI_FW_MODULE.MODULE_LEVEL
     *
     * @ibatorgenerated Thu Sep 25 15:11:52 CST 2014
     */
    private Short moduleLevel;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column UI_FW_MODULE.PARENT_ID
     *
     * @ibatorgenerated Thu Sep 25 15:11:52 CST 2014
     */
    private Integer parentId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column UI_FW_MODULE.SORT
     *
     * @ibatorgenerated Thu Sep 25 15:11:52 CST 2014
     */
    private Integer sort;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column UI_FW_MODULE.VIEW_TYPE
     *
     * @ibatorgenerated Thu Sep 25 15:11:52 CST 2014
     */
    private String viewType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column UI_FW_MODULE.IMG_URL
     *
     * @ibatorgenerated Thu Sep 25 15:11:52 CST 2014
     */
    private String imgUrl;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column UI_FW_MODULE.CREATE_TIME
     *
     * @ibatorgenerated Thu Sep 25 15:11:52 CST 2014
     */
    private Date createTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column UI_FW_MODULE.UPDATE_TIME
     *
     * @ibatorgenerated Thu Sep 25 15:11:52 CST 2014
     */
    private Date updateTime;
    
    private List<UiFwFunction> functions;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column UI_FW_MODULE.ID
     *
     * @return the value of UI_FW_MODULE.ID
     *
     * @ibatorgenerated Thu Sep 25 15:11:52 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column UI_FW_MODULE.ID
     *
     * @param id the value for UI_FW_MODULE.ID
     *
     * @ibatorgenerated Thu Sep 25 15:11:52 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column UI_FW_MODULE.NAME
     *
     * @return the value of UI_FW_MODULE.NAME
     *
     * @ibatorgenerated Thu Sep 25 15:11:52 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column UI_FW_MODULE.NAME
     *
     * @param name the value for UI_FW_MODULE.NAME
     *
     * @ibatorgenerated Thu Sep 25 15:11:52 CST 2014
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column UI_FW_MODULE.ACTION_URL
     *
     * @return the value of UI_FW_MODULE.ACTION_URL
     *
     * @ibatorgenerated Thu Sep 25 15:11:52 CST 2014
     */
    public String getActionUrl() {
        return actionUrl;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column UI_FW_MODULE.ACTION_URL
     *
     * @param actionUrl the value for UI_FW_MODULE.ACTION_URL
     *
     * @ibatorgenerated Thu Sep 25 15:11:52 CST 2014
     */
    public void setActionUrl(String actionUrl) {
        this.actionUrl = actionUrl;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column UI_FW_MODULE.MODULE_LEVEL
     *
     * @return the value of UI_FW_MODULE.MODULE_LEVEL
     *
     * @ibatorgenerated Thu Sep 25 15:11:52 CST 2014
     */
    public Short getModuleLevel() {
        return moduleLevel;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column UI_FW_MODULE.MODULE_LEVEL
     *
     * @param moduleLevel the value for UI_FW_MODULE.MODULE_LEVEL
     *
     * @ibatorgenerated Thu Sep 25 15:11:52 CST 2014
     */
    public void setModuleLevel(Short moduleLevel) {
        this.moduleLevel = moduleLevel;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column UI_FW_MODULE.PARENT_ID
     *
     * @return the value of UI_FW_MODULE.PARENT_ID
     *
     * @ibatorgenerated Thu Sep 25 15:11:52 CST 2014
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column UI_FW_MODULE.PARENT_ID
     *
     * @param parentId the value for UI_FW_MODULE.PARENT_ID
     *
     * @ibatorgenerated Thu Sep 25 15:11:52 CST 2014
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column UI_FW_MODULE.SORT
     *
     * @return the value of UI_FW_MODULE.SORT
     *
     * @ibatorgenerated Thu Sep 25 15:11:52 CST 2014
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column UI_FW_MODULE.SORT
     *
     * @param sort the value for UI_FW_MODULE.SORT
     *
     * @ibatorgenerated Thu Sep 25 15:11:52 CST 2014
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column UI_FW_MODULE.VIEW_TYPE
     *
     * @return the value of UI_FW_MODULE.VIEW_TYPE
     *
     * @ibatorgenerated Thu Sep 25 15:11:52 CST 2014
     */
    public String getViewType() {
        return viewType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column UI_FW_MODULE.VIEW_TYPE
     *
     * @param viewType the value for UI_FW_MODULE.VIEW_TYPE
     *
     * @ibatorgenerated Thu Sep 25 15:11:52 CST 2014
     */
    public void setViewType(String viewType) {
        this.viewType = viewType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column UI_FW_MODULE.IMG_URL
     *
     * @return the value of UI_FW_MODULE.IMG_URL
     *
     * @ibatorgenerated Thu Sep 25 15:11:52 CST 2014
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column UI_FW_MODULE.IMG_URL
     *
     * @param imgUrl the value for UI_FW_MODULE.IMG_URL
     *
     * @ibatorgenerated Thu Sep 25 15:11:52 CST 2014
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column UI_FW_MODULE.CREATE_TIME
     *
     * @return the value of UI_FW_MODULE.CREATE_TIME
     *
     * @ibatorgenerated Thu Sep 25 15:11:52 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column UI_FW_MODULE.CREATE_TIME
     *
     * @param createTime the value for UI_FW_MODULE.CREATE_TIME
     *
     * @ibatorgenerated Thu Sep 25 15:11:52 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column UI_FW_MODULE.UPDATE_TIME
     *
     * @return the value of UI_FW_MODULE.UPDATE_TIME
     *
     * @ibatorgenerated Thu Sep 25 15:11:52 CST 2014
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column UI_FW_MODULE.UPDATE_TIME
     *
     * @param updateTime the value for UI_FW_MODULE.UPDATE_TIME
     *
     * @ibatorgenerated Thu Sep 25 15:11:52 CST 2014
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

	public List<UiFwFunction> getFunctions() {
		return functions;
	}

	public void setFunctions(List<UiFwFunction> functions) {
		this.functions = functions;
	}
    
}