package com.gfan.report.frame.module;

import java.util.Date;

public class UiFwFunction {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column UI_FW_FUNCTION.ID
     *
     * @ibatorgenerated Thu Sep 25 15:11:46 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column UI_FW_FUNCTION.NAME
     *
     * @ibatorgenerated Thu Sep 25 15:11:46 CST 2014
     */
    private String name;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column UI_FW_FUNCTION.ACTION_URL
     *
     * @ibatorgenerated Thu Sep 25 15:11:46 CST 2014
     */
    private String actionUrl;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column UI_FW_FUNCTION.MODULE_ID
     *
     * @ibatorgenerated Thu Sep 25 15:11:46 CST 2014
     */
    private Integer moduleId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column UI_FW_FUNCTION.ONLINE_STATUS
     *
     * @ibatorgenerated Thu Sep 25 15:11:46 CST 2014
     */
    private Short onlineStatus;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column UI_FW_FUNCTION.SORT
     *
     * @ibatorgenerated Thu Sep 25 15:11:46 CST 2014
     */
    private Integer sort;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column UI_FW_FUNCTION.READ_CACHE
     *
     * @ibatorgenerated Thu Sep 25 15:11:46 CST 2014
     */
    private Short readCache;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column UI_FW_FUNCTION.IS_HIDE
     *
     * @ibatorgenerated Thu Sep 25 15:11:46 CST 2014
     */
    private Boolean isHide;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column UI_FW_FUNCTION.CREATE_TIME
     *
     * @ibatorgenerated Thu Sep 25 15:11:46 CST 2014
     */
    private Date createTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column UI_FW_FUNCTION.UPDATE_TIME
     *
     * @ibatorgenerated Thu Sep 25 15:11:46 CST 2014
     */
    private Date updateTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column UI_FW_FUNCTION.FUNCTION_TYPE
     *
     * @ibatorgenerated Thu Sep 25 15:11:46 CST 2014
     */
    private Short functionType;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column UI_FW_FUNCTION.ID
     *
     * @return the value of UI_FW_FUNCTION.ID
     *
     * @ibatorgenerated Thu Sep 25 15:11:46 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column UI_FW_FUNCTION.ID
     *
     * @param id the value for UI_FW_FUNCTION.ID
     *
     * @ibatorgenerated Thu Sep 25 15:11:46 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column UI_FW_FUNCTION.NAME
     *
     * @return the value of UI_FW_FUNCTION.NAME
     *
     * @ibatorgenerated Thu Sep 25 15:11:46 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column UI_FW_FUNCTION.NAME
     *
     * @param name the value for UI_FW_FUNCTION.NAME
     *
     * @ibatorgenerated Thu Sep 25 15:11:46 CST 2014
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column UI_FW_FUNCTION.ACTION_URL
     *
     * @return the value of UI_FW_FUNCTION.ACTION_URL
     *
     * @ibatorgenerated Thu Sep 25 15:11:46 CST 2014
     */
    public String getActionUrl() {
        return actionUrl;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column UI_FW_FUNCTION.ACTION_URL
     *
     * @param actionUrl the value for UI_FW_FUNCTION.ACTION_URL
     *
     * @ibatorgenerated Thu Sep 25 15:11:46 CST 2014
     */
    public void setActionUrl(String actionUrl) {
        this.actionUrl = actionUrl;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column UI_FW_FUNCTION.MODULE_ID
     *
     * @return the value of UI_FW_FUNCTION.MODULE_ID
     *
     * @ibatorgenerated Thu Sep 25 15:11:46 CST 2014
     */
    public Integer getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column UI_FW_FUNCTION.MODULE_ID
     *
     * @param moduleId the value for UI_FW_FUNCTION.MODULE_ID
     *
     * @ibatorgenerated Thu Sep 25 15:11:46 CST 2014
     */
    public void setModuleId(Integer moduleId) {
        this.moduleId = moduleId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column UI_FW_FUNCTION.ONLINE_STATUS
     *
     * @return the value of UI_FW_FUNCTION.ONLINE_STATUS
     *
     * @ibatorgenerated Thu Sep 25 15:11:46 CST 2014
     */
    public Short getOnlineStatus() {
        return onlineStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column UI_FW_FUNCTION.ONLINE_STATUS
     *
     * @param onlineStatus the value for UI_FW_FUNCTION.ONLINE_STATUS
     *
     * @ibatorgenerated Thu Sep 25 15:11:46 CST 2014
     */
    public void setOnlineStatus(Short onlineStatus) {
        this.onlineStatus = onlineStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column UI_FW_FUNCTION.SORT
     *
     * @return the value of UI_FW_FUNCTION.SORT
     *
     * @ibatorgenerated Thu Sep 25 15:11:46 CST 2014
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column UI_FW_FUNCTION.SORT
     *
     * @param sort the value for UI_FW_FUNCTION.SORT
     *
     * @ibatorgenerated Thu Sep 25 15:11:46 CST 2014
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column UI_FW_FUNCTION.READ_CACHE
     *
     * @return the value of UI_FW_FUNCTION.READ_CACHE
     *
     * @ibatorgenerated Thu Sep 25 15:11:46 CST 2014
     */
    public Short getReadCache() {
        return readCache;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column UI_FW_FUNCTION.READ_CACHE
     *
     * @param readCache the value for UI_FW_FUNCTION.READ_CACHE
     *
     * @ibatorgenerated Thu Sep 25 15:11:46 CST 2014
     */
    public void setReadCache(Short readCache) {
        this.readCache = readCache;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column UI_FW_FUNCTION.IS_HIDE
     *
     * @return the value of UI_FW_FUNCTION.IS_HIDE
     *
     * @ibatorgenerated Thu Sep 25 15:11:46 CST 2014
     */
    public Boolean getIsHide() {
        return isHide;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column UI_FW_FUNCTION.IS_HIDE
     *
     * @param isHide the value for UI_FW_FUNCTION.IS_HIDE
     *
     * @ibatorgenerated Thu Sep 25 15:11:46 CST 2014
     */
    public void setIsHide(Boolean isHide) {
        this.isHide = isHide;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column UI_FW_FUNCTION.CREATE_TIME
     *
     * @return the value of UI_FW_FUNCTION.CREATE_TIME
     *
     * @ibatorgenerated Thu Sep 25 15:11:46 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column UI_FW_FUNCTION.CREATE_TIME
     *
     * @param createTime the value for UI_FW_FUNCTION.CREATE_TIME
     *
     * @ibatorgenerated Thu Sep 25 15:11:46 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column UI_FW_FUNCTION.UPDATE_TIME
     *
     * @return the value of UI_FW_FUNCTION.UPDATE_TIME
     *
     * @ibatorgenerated Thu Sep 25 15:11:46 CST 2014
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column UI_FW_FUNCTION.UPDATE_TIME
     *
     * @param updateTime the value for UI_FW_FUNCTION.UPDATE_TIME
     *
     * @ibatorgenerated Thu Sep 25 15:11:46 CST 2014
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column UI_FW_FUNCTION.FUNCTION_TYPE
     *
     * @return the value of UI_FW_FUNCTION.FUNCTION_TYPE
     *
     * @ibatorgenerated Thu Sep 25 15:11:46 CST 2014
     */
    public Short getFunctionType() {
        return functionType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column UI_FW_FUNCTION.FUNCTION_TYPE
     *
     * @param functionType the value for UI_FW_FUNCTION.FUNCTION_TYPE
     *
     * @ibatorgenerated Thu Sep 25 15:11:46 CST 2014
     */
    public void setFunctionType(Short functionType) {
        this.functionType = functionType;
    }
}