package com.gfan.report.frame.module;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class UiFwFunctionExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table UI_FW_FUNCTION
     *
     * @ibatorgenerated Thu Sep 25 15:11:46 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table UI_FW_FUNCTION
     *
     * @ibatorgenerated Thu Sep 25 15:11:46 CST 2014
     */
    protected List oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_FUNCTION
     *
     * @ibatorgenerated Thu Sep 25 15:11:46 CST 2014
     */
    public UiFwFunctionExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_FUNCTION
     *
     * @ibatorgenerated Thu Sep 25 15:11:46 CST 2014
     */
    protected UiFwFunctionExample(UiFwFunctionExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_FUNCTION
     *
     * @ibatorgenerated Thu Sep 25 15:11:46 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_FUNCTION
     *
     * @ibatorgenerated Thu Sep 25 15:11:46 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_FUNCTION
     *
     * @ibatorgenerated Thu Sep 25 15:11:46 CST 2014
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_FUNCTION
     *
     * @ibatorgenerated Thu Sep 25 15:11:46 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_FUNCTION
     *
     * @ibatorgenerated Thu Sep 25 15:11:46 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_FUNCTION
     *
     * @ibatorgenerated Thu Sep 25 15:11:46 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_FUNCTION
     *
     * @ibatorgenerated Thu Sep 25 15:11:46 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table UI_FW_FUNCTION
     *
     * @ibatorgenerated Thu Sep 25 15:11:46 CST 2014
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return this;
        }

        public Criteria andIdIn(List values) {
            addCriterion("ID in", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List values) {
            addCriterion("ID not in", values, "id");
            return this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return this;
        }

        public Criteria andNameIsNull() {
            addCriterion("NAME is null");
            return this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("NAME is not null");
            return this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("NAME =", value, "name");
            return this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("NAME <>", value, "name");
            return this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("NAME >", value, "name");
            return this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("NAME >=", value, "name");
            return this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("NAME <", value, "name");
            return this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("NAME <=", value, "name");
            return this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("NAME like", value, "name");
            return this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("NAME not like", value, "name");
            return this;
        }

        public Criteria andNameIn(List values) {
            addCriterion("NAME in", values, "name");
            return this;
        }

        public Criteria andNameNotIn(List values) {
            addCriterion("NAME not in", values, "name");
            return this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("NAME between", value1, value2, "name");
            return this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("NAME not between", value1, value2, "name");
            return this;
        }

        public Criteria andActionUrlIsNull() {
            addCriterion("ACTION_URL is null");
            return this;
        }

        public Criteria andActionUrlIsNotNull() {
            addCriterion("ACTION_URL is not null");
            return this;
        }

        public Criteria andActionUrlEqualTo(String value) {
            addCriterion("ACTION_URL =", value, "actionUrl");
            return this;
        }

        public Criteria andActionUrlNotEqualTo(String value) {
            addCriterion("ACTION_URL <>", value, "actionUrl");
            return this;
        }

        public Criteria andActionUrlGreaterThan(String value) {
            addCriterion("ACTION_URL >", value, "actionUrl");
            return this;
        }

        public Criteria andActionUrlGreaterThanOrEqualTo(String value) {
            addCriterion("ACTION_URL >=", value, "actionUrl");
            return this;
        }

        public Criteria andActionUrlLessThan(String value) {
            addCriterion("ACTION_URL <", value, "actionUrl");
            return this;
        }

        public Criteria andActionUrlLessThanOrEqualTo(String value) {
            addCriterion("ACTION_URL <=", value, "actionUrl");
            return this;
        }

        public Criteria andActionUrlLike(String value) {
            addCriterion("ACTION_URL like", value, "actionUrl");
            return this;
        }

        public Criteria andActionUrlNotLike(String value) {
            addCriterion("ACTION_URL not like", value, "actionUrl");
            return this;
        }

        public Criteria andActionUrlIn(List values) {
            addCriterion("ACTION_URL in", values, "actionUrl");
            return this;
        }

        public Criteria andActionUrlNotIn(List values) {
            addCriterion("ACTION_URL not in", values, "actionUrl");
            return this;
        }

        public Criteria andActionUrlBetween(String value1, String value2) {
            addCriterion("ACTION_URL between", value1, value2, "actionUrl");
            return this;
        }

        public Criteria andActionUrlNotBetween(String value1, String value2) {
            addCriterion("ACTION_URL not between", value1, value2, "actionUrl");
            return this;
        }

        public Criteria andModuleIdIsNull() {
            addCriterion("MODULE_ID is null");
            return this;
        }

        public Criteria andModuleIdIsNotNull() {
            addCriterion("MODULE_ID is not null");
            return this;
        }

        public Criteria andModuleIdEqualTo(Integer value) {
            addCriterion("MODULE_ID =", value, "moduleId");
            return this;
        }

        public Criteria andModuleIdNotEqualTo(Integer value) {
            addCriterion("MODULE_ID <>", value, "moduleId");
            return this;
        }

        public Criteria andModuleIdGreaterThan(Integer value) {
            addCriterion("MODULE_ID >", value, "moduleId");
            return this;
        }

        public Criteria andModuleIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("MODULE_ID >=", value, "moduleId");
            return this;
        }

        public Criteria andModuleIdLessThan(Integer value) {
            addCriterion("MODULE_ID <", value, "moduleId");
            return this;
        }

        public Criteria andModuleIdLessThanOrEqualTo(Integer value) {
            addCriterion("MODULE_ID <=", value, "moduleId");
            return this;
        }

        public Criteria andModuleIdIn(List values) {
            addCriterion("MODULE_ID in", values, "moduleId");
            return this;
        }

        public Criteria andModuleIdNotIn(List values) {
            addCriterion("MODULE_ID not in", values, "moduleId");
            return this;
        }

        public Criteria andModuleIdBetween(Integer value1, Integer value2) {
            addCriterion("MODULE_ID between", value1, value2, "moduleId");
            return this;
        }

        public Criteria andModuleIdNotBetween(Integer value1, Integer value2) {
            addCriterion("MODULE_ID not between", value1, value2, "moduleId");
            return this;
        }

        public Criteria andOnlineStatusIsNull() {
            addCriterion("ONLINE_STATUS is null");
            return this;
        }

        public Criteria andOnlineStatusIsNotNull() {
            addCriterion("ONLINE_STATUS is not null");
            return this;
        }

        public Criteria andOnlineStatusEqualTo(Short value) {
            addCriterion("ONLINE_STATUS =", value, "onlineStatus");
            return this;
        }

        public Criteria andOnlineStatusNotEqualTo(Short value) {
            addCriterion("ONLINE_STATUS <>", value, "onlineStatus");
            return this;
        }

        public Criteria andOnlineStatusGreaterThan(Short value) {
            addCriterion("ONLINE_STATUS >", value, "onlineStatus");
            return this;
        }

        public Criteria andOnlineStatusGreaterThanOrEqualTo(Short value) {
            addCriterion("ONLINE_STATUS >=", value, "onlineStatus");
            return this;
        }

        public Criteria andOnlineStatusLessThan(Short value) {
            addCriterion("ONLINE_STATUS <", value, "onlineStatus");
            return this;
        }

        public Criteria andOnlineStatusLessThanOrEqualTo(Short value) {
            addCriterion("ONLINE_STATUS <=", value, "onlineStatus");
            return this;
        }

        public Criteria andOnlineStatusIn(List values) {
            addCriterion("ONLINE_STATUS in", values, "onlineStatus");
            return this;
        }

        public Criteria andOnlineStatusNotIn(List values) {
            addCriterion("ONLINE_STATUS not in", values, "onlineStatus");
            return this;
        }

        public Criteria andOnlineStatusBetween(Short value1, Short value2) {
            addCriterion("ONLINE_STATUS between", value1, value2, "onlineStatus");
            return this;
        }

        public Criteria andOnlineStatusNotBetween(Short value1, Short value2) {
            addCriterion("ONLINE_STATUS not between", value1, value2, "onlineStatus");
            return this;
        }

        public Criteria andSortIsNull() {
            addCriterion("SORT is null");
            return this;
        }

        public Criteria andSortIsNotNull() {
            addCriterion("SORT is not null");
            return this;
        }

        public Criteria andSortEqualTo(Integer value) {
            addCriterion("SORT =", value, "sort");
            return this;
        }

        public Criteria andSortNotEqualTo(Integer value) {
            addCriterion("SORT <>", value, "sort");
            return this;
        }

        public Criteria andSortGreaterThan(Integer value) {
            addCriterion("SORT >", value, "sort");
            return this;
        }

        public Criteria andSortGreaterThanOrEqualTo(Integer value) {
            addCriterion("SORT >=", value, "sort");
            return this;
        }

        public Criteria andSortLessThan(Integer value) {
            addCriterion("SORT <", value, "sort");
            return this;
        }

        public Criteria andSortLessThanOrEqualTo(Integer value) {
            addCriterion("SORT <=", value, "sort");
            return this;
        }

        public Criteria andSortIn(List values) {
            addCriterion("SORT in", values, "sort");
            return this;
        }

        public Criteria andSortNotIn(List values) {
            addCriterion("SORT not in", values, "sort");
            return this;
        }

        public Criteria andSortBetween(Integer value1, Integer value2) {
            addCriterion("SORT between", value1, value2, "sort");
            return this;
        }

        public Criteria andSortNotBetween(Integer value1, Integer value2) {
            addCriterion("SORT not between", value1, value2, "sort");
            return this;
        }

        public Criteria andReadCacheIsNull() {
            addCriterion("READ_CACHE is null");
            return this;
        }

        public Criteria andReadCacheIsNotNull() {
            addCriterion("READ_CACHE is not null");
            return this;
        }

        public Criteria andReadCacheEqualTo(Short value) {
            addCriterion("READ_CACHE =", value, "readCache");
            return this;
        }

        public Criteria andReadCacheNotEqualTo(Short value) {
            addCriterion("READ_CACHE <>", value, "readCache");
            return this;
        }

        public Criteria andReadCacheGreaterThan(Short value) {
            addCriterion("READ_CACHE >", value, "readCache");
            return this;
        }

        public Criteria andReadCacheGreaterThanOrEqualTo(Short value) {
            addCriterion("READ_CACHE >=", value, "readCache");
            return this;
        }

        public Criteria andReadCacheLessThan(Short value) {
            addCriterion("READ_CACHE <", value, "readCache");
            return this;
        }

        public Criteria andReadCacheLessThanOrEqualTo(Short value) {
            addCriterion("READ_CACHE <=", value, "readCache");
            return this;
        }

        public Criteria andReadCacheIn(List values) {
            addCriterion("READ_CACHE in", values, "readCache");
            return this;
        }

        public Criteria andReadCacheNotIn(List values) {
            addCriterion("READ_CACHE not in", values, "readCache");
            return this;
        }

        public Criteria andReadCacheBetween(Short value1, Short value2) {
            addCriterion("READ_CACHE between", value1, value2, "readCache");
            return this;
        }

        public Criteria andReadCacheNotBetween(Short value1, Short value2) {
            addCriterion("READ_CACHE not between", value1, value2, "readCache");
            return this;
        }

        public Criteria andIsHideIsNull() {
            addCriterion("IS_HIDE is null");
            return this;
        }

        public Criteria andIsHideIsNotNull() {
            addCriterion("IS_HIDE is not null");
            return this;
        }

        public Criteria andIsHideEqualTo(Boolean value) {
            addCriterion("IS_HIDE =", value, "isHide");
            return this;
        }

        public Criteria andIsHideNotEqualTo(Boolean value) {
            addCriterion("IS_HIDE <>", value, "isHide");
            return this;
        }

        public Criteria andIsHideGreaterThan(Boolean value) {
            addCriterion("IS_HIDE >", value, "isHide");
            return this;
        }

        public Criteria andIsHideGreaterThanOrEqualTo(Boolean value) {
            addCriterion("IS_HIDE >=", value, "isHide");
            return this;
        }

        public Criteria andIsHideLessThan(Boolean value) {
            addCriterion("IS_HIDE <", value, "isHide");
            return this;
        }

        public Criteria andIsHideLessThanOrEqualTo(Boolean value) {
            addCriterion("IS_HIDE <=", value, "isHide");
            return this;
        }

        public Criteria andIsHideIn(List values) {
            addCriterion("IS_HIDE in", values, "isHide");
            return this;
        }

        public Criteria andIsHideNotIn(List values) {
            addCriterion("IS_HIDE not in", values, "isHide");
            return this;
        }

        public Criteria andIsHideBetween(Boolean value1, Boolean value2) {
            addCriterion("IS_HIDE between", value1, value2, "isHide");
            return this;
        }

        public Criteria andIsHideNotBetween(Boolean value1, Boolean value2) {
            addCriterion("IS_HIDE not between", value1, value2, "isHide");
            return this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeIn(List values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotIn(List values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeIn(List values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotIn(List values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return this;
        }

        public Criteria andFunctionTypeIsNull() {
            addCriterion("FUNCTION_TYPE is null");
            return this;
        }

        public Criteria andFunctionTypeIsNotNull() {
            addCriterion("FUNCTION_TYPE is not null");
            return this;
        }

        public Criteria andFunctionTypeEqualTo(Short value) {
            addCriterion("FUNCTION_TYPE =", value, "functionType");
            return this;
        }

        public Criteria andFunctionTypeNotEqualTo(Short value) {
            addCriterion("FUNCTION_TYPE <>", value, "functionType");
            return this;
        }

        public Criteria andFunctionTypeGreaterThan(Short value) {
            addCriterion("FUNCTION_TYPE >", value, "functionType");
            return this;
        }

        public Criteria andFunctionTypeGreaterThanOrEqualTo(Short value) {
            addCriterion("FUNCTION_TYPE >=", value, "functionType");
            return this;
        }

        public Criteria andFunctionTypeLessThan(Short value) {
            addCriterion("FUNCTION_TYPE <", value, "functionType");
            return this;
        }

        public Criteria andFunctionTypeLessThanOrEqualTo(Short value) {
            addCriterion("FUNCTION_TYPE <=", value, "functionType");
            return this;
        }

        public Criteria andFunctionTypeIn(List values) {
            addCriterion("FUNCTION_TYPE in", values, "functionType");
            return this;
        }

        public Criteria andFunctionTypeNotIn(List values) {
            addCriterion("FUNCTION_TYPE not in", values, "functionType");
            return this;
        }

        public Criteria andFunctionTypeBetween(Short value1, Short value2) {
            addCriterion("FUNCTION_TYPE between", value1, value2, "functionType");
            return this;
        }

        public Criteria andFunctionTypeNotBetween(Short value1, Short value2) {
            addCriterion("FUNCTION_TYPE not between", value1, value2, "functionType");
            return this;
        }
    }
}