package com.gfan.report.frame.module;

public class UiFwRoleFunctionLinkKey {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column UI_FW_ROLE_FUNCTION_LINK.FUNCTION_ID
     *
     * @ibatorgenerated Mon May 11 16:32:54 CST 2015
     */
    private Integer functionId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column UI_FW_ROLE_FUNCTION_LINK.ROLE_ID
     *
     * @ibatorgenerated Mon May 11 16:32:54 CST 2015
     */
    private Integer roleId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column UI_FW_ROLE_FUNCTION_LINK.FUNCTION_ID
     *
     * @return the value of UI_FW_ROLE_FUNCTION_LINK.FUNCTION_ID
     *
     * @ibatorgenerated Mon May 11 16:32:54 CST 2015
     */
    public Integer getFunctionId() {
        return functionId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column UI_FW_ROLE_FUNCTION_LINK.FUNCTION_ID
     *
     * @param functionId the value for UI_FW_ROLE_FUNCTION_LINK.FUNCTION_ID
     *
     * @ibatorgenerated Mon May 11 16:32:54 CST 2015
     */
    public void setFunctionId(Integer functionId) {
        this.functionId = functionId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column UI_FW_ROLE_FUNCTION_LINK.ROLE_ID
     *
     * @return the value of UI_FW_ROLE_FUNCTION_LINK.ROLE_ID
     *
     * @ibatorgenerated Mon May 11 16:32:54 CST 2015
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column UI_FW_ROLE_FUNCTION_LINK.ROLE_ID
     *
     * @param roleId the value for UI_FW_ROLE_FUNCTION_LINK.ROLE_ID
     *
     * @ibatorgenerated Mon May 11 16:32:54 CST 2015
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}