package com.gfan.report.frame.module;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class UiFwRoleFunctionLinkExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table UI_FW_ROLE_FUNCTION_LINK
     *
     * @ibatorgenerated Mon May 11 16:32:54 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table UI_FW_ROLE_FUNCTION_LINK
     *
     * @ibatorgenerated Mon May 11 16:32:54 CST 2015
     */
    protected List oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_ROLE_FUNCTION_LINK
     *
     * @ibatorgenerated Mon May 11 16:32:54 CST 2015
     */
    public UiFwRoleFunctionLinkExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_ROLE_FUNCTION_LINK
     *
     * @ibatorgenerated Mon May 11 16:32:54 CST 2015
     */
    protected UiFwRoleFunctionLinkExample(UiFwRoleFunctionLinkExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_ROLE_FUNCTION_LINK
     *
     * @ibatorgenerated Mon May 11 16:32:54 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_ROLE_FUNCTION_LINK
     *
     * @ibatorgenerated Mon May 11 16:32:54 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_ROLE_FUNCTION_LINK
     *
     * @ibatorgenerated Mon May 11 16:32:54 CST 2015
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_ROLE_FUNCTION_LINK
     *
     * @ibatorgenerated Mon May 11 16:32:54 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_ROLE_FUNCTION_LINK
     *
     * @ibatorgenerated Mon May 11 16:32:54 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_ROLE_FUNCTION_LINK
     *
     * @ibatorgenerated Mon May 11 16:32:54 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_ROLE_FUNCTION_LINK
     *
     * @ibatorgenerated Mon May 11 16:32:54 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table UI_FW_ROLE_FUNCTION_LINK
     *
     * @ibatorgenerated Mon May 11 16:32:54 CST 2015
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andFunctionIdIsNull() {
            addCriterion("FUNCTION_ID is null");
            return this;
        }

        public Criteria andFunctionIdIsNotNull() {
            addCriterion("FUNCTION_ID is not null");
            return this;
        }

        public Criteria andFunctionIdEqualTo(Integer value) {
            addCriterion("FUNCTION_ID =", value, "functionId");
            return this;
        }

        public Criteria andFunctionIdNotEqualTo(Integer value) {
            addCriterion("FUNCTION_ID <>", value, "functionId");
            return this;
        }

        public Criteria andFunctionIdGreaterThan(Integer value) {
            addCriterion("FUNCTION_ID >", value, "functionId");
            return this;
        }

        public Criteria andFunctionIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("FUNCTION_ID >=", value, "functionId");
            return this;
        }

        public Criteria andFunctionIdLessThan(Integer value) {
            addCriterion("FUNCTION_ID <", value, "functionId");
            return this;
        }

        public Criteria andFunctionIdLessThanOrEqualTo(Integer value) {
            addCriterion("FUNCTION_ID <=", value, "functionId");
            return this;
        }

        public Criteria andFunctionIdIn(List values) {
            addCriterion("FUNCTION_ID in", values, "functionId");
            return this;
        }

        public Criteria andFunctionIdNotIn(List values) {
            addCriterion("FUNCTION_ID not in", values, "functionId");
            return this;
        }

        public Criteria andFunctionIdBetween(Integer value1, Integer value2) {
            addCriterion("FUNCTION_ID between", value1, value2, "functionId");
            return this;
        }

        public Criteria andFunctionIdNotBetween(Integer value1, Integer value2) {
            addCriterion("FUNCTION_ID not between", value1, value2, "functionId");
            return this;
        }

        public Criteria andRoleIdIsNull() {
            addCriterion("ROLE_ID is null");
            return this;
        }

        public Criteria andRoleIdIsNotNull() {
            addCriterion("ROLE_ID is not null");
            return this;
        }

        public Criteria andRoleIdEqualTo(Integer value) {
            addCriterion("ROLE_ID =", value, "roleId");
            return this;
        }

        public Criteria andRoleIdNotEqualTo(Integer value) {
            addCriterion("ROLE_ID <>", value, "roleId");
            return this;
        }

        public Criteria andRoleIdGreaterThan(Integer value) {
            addCriterion("ROLE_ID >", value, "roleId");
            return this;
        }

        public Criteria andRoleIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ROLE_ID >=", value, "roleId");
            return this;
        }

        public Criteria andRoleIdLessThan(Integer value) {
            addCriterion("ROLE_ID <", value, "roleId");
            return this;
        }

        public Criteria andRoleIdLessThanOrEqualTo(Integer value) {
            addCriterion("ROLE_ID <=", value, "roleId");
            return this;
        }

        public Criteria andRoleIdIn(List values) {
            addCriterion("ROLE_ID in", values, "roleId");
            return this;
        }

        public Criteria andRoleIdNotIn(List values) {
            addCriterion("ROLE_ID not in", values, "roleId");
            return this;
        }

        public Criteria andRoleIdBetween(Integer value1, Integer value2) {
            addCriterion("ROLE_ID between", value1, value2, "roleId");
            return this;
        }

        public Criteria andRoleIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ROLE_ID not between", value1, value2, "roleId");
            return this;
        }
    }
}