package com.gfan.report.frame.module;

import java.util.Date;

public class UiFwFunctionWidget {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column UI_FW_FUNCTION_WIDGET.ID
     *
     * @ibatorgenerated Thu Sep 25 18:12:08 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column UI_FW_FUNCTION_WIDGET.NAME
     *
     * @ibatorgenerated Thu Sep 25 18:12:08 CST 2014
     */
    private String name;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column UI_FW_FUNCTION_WIDGET.ACTION_URL
     *
     * @ibatorgenerated Thu Sep 25 18:12:08 CST 2014
     */
    private String actionUrl;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column UI_FW_FUNCTION_WIDGET.WIDGET_TYPE
     *
     * @ibatorgenerated Thu Sep 25 18:12:08 CST 2014
     */
    private Short widgetType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column UI_FW_FUNCTION_WIDGET.FUNCTION_ID
     *
     * @ibatorgenerated Thu Sep 25 18:12:08 CST 2014
     */
    private Integer functionId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column UI_FW_FUNCTION_WIDGET.SORT
     *
     * @ibatorgenerated Thu Sep 25 18:12:08 CST 2014
     */
    private Integer sort;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column UI_FW_FUNCTION_WIDGET.LEVEL
     *
     * @ibatorgenerated Thu Sep 25 18:12:08 CST 2014
     */
    private Short level;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column UI_FW_FUNCTION_WIDGET.ENABLE_CACHE
     *
     * @ibatorgenerated Thu Sep 25 18:12:08 CST 2014
     */
    private Integer enableCache;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column UI_FW_FUNCTION_WIDGET.PARENT_ID
     *
     * @ibatorgenerated Thu Sep 25 18:12:08 CST 2014
     */
    private Integer parentId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column UI_FW_FUNCTION_WIDGET.CREATE_TIME
     *
     * @ibatorgenerated Thu Sep 25 18:12:08 CST 2014
     */
    private Date createTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column UI_FW_FUNCTION_WIDGET.UPDATE_TIME
     *
     * @ibatorgenerated Thu Sep 25 18:12:08 CST 2014
     */
    private Date updateTime;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column UI_FW_FUNCTION_WIDGET.ID
     *
     * @return the value of UI_FW_FUNCTION_WIDGET.ID
     *
     * @ibatorgenerated Thu Sep 25 18:12:08 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column UI_FW_FUNCTION_WIDGET.ID
     *
     * @param id the value for UI_FW_FUNCTION_WIDGET.ID
     *
     * @ibatorgenerated Thu Sep 25 18:12:08 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column UI_FW_FUNCTION_WIDGET.NAME
     *
     * @return the value of UI_FW_FUNCTION_WIDGET.NAME
     *
     * @ibatorgenerated Thu Sep 25 18:12:08 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column UI_FW_FUNCTION_WIDGET.NAME
     *
     * @param name the value for UI_FW_FUNCTION_WIDGET.NAME
     *
     * @ibatorgenerated Thu Sep 25 18:12:08 CST 2014
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column UI_FW_FUNCTION_WIDGET.ACTION_URL
     *
     * @return the value of UI_FW_FUNCTION_WIDGET.ACTION_URL
     *
     * @ibatorgenerated Thu Sep 25 18:12:08 CST 2014
     */
    public String getActionUrl() {
        return actionUrl;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column UI_FW_FUNCTION_WIDGET.ACTION_URL
     *
     * @param actionUrl the value for UI_FW_FUNCTION_WIDGET.ACTION_URL
     *
     * @ibatorgenerated Thu Sep 25 18:12:08 CST 2014
     */
    public void setActionUrl(String actionUrl) {
        this.actionUrl = actionUrl;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column UI_FW_FUNCTION_WIDGET.WIDGET_TYPE
     *
     * @return the value of UI_FW_FUNCTION_WIDGET.WIDGET_TYPE
     *
     * @ibatorgenerated Thu Sep 25 18:12:08 CST 2014
     */
    public Short getWidgetType() {
        return widgetType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column UI_FW_FUNCTION_WIDGET.WIDGET_TYPE
     *
     * @param widgetType the value for UI_FW_FUNCTION_WIDGET.WIDGET_TYPE
     *
     * @ibatorgenerated Thu Sep 25 18:12:08 CST 2014
     */
    public void setWidgetType(Short widgetType) {
        this.widgetType = widgetType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column UI_FW_FUNCTION_WIDGET.FUNCTION_ID
     *
     * @return the value of UI_FW_FUNCTION_WIDGET.FUNCTION_ID
     *
     * @ibatorgenerated Thu Sep 25 18:12:08 CST 2014
     */
    public Integer getFunctionId() {
        return functionId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column UI_FW_FUNCTION_WIDGET.FUNCTION_ID
     *
     * @param functionId the value for UI_FW_FUNCTION_WIDGET.FUNCTION_ID
     *
     * @ibatorgenerated Thu Sep 25 18:12:08 CST 2014
     */
    public void setFunctionId(Integer functionId) {
        this.functionId = functionId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column UI_FW_FUNCTION_WIDGET.SORT
     *
     * @return the value of UI_FW_FUNCTION_WIDGET.SORT
     *
     * @ibatorgenerated Thu Sep 25 18:12:08 CST 2014
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column UI_FW_FUNCTION_WIDGET.SORT
     *
     * @param sort the value for UI_FW_FUNCTION_WIDGET.SORT
     *
     * @ibatorgenerated Thu Sep 25 18:12:08 CST 2014
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column UI_FW_FUNCTION_WIDGET.LEVEL
     *
     * @return the value of UI_FW_FUNCTION_WIDGET.LEVEL
     *
     * @ibatorgenerated Thu Sep 25 18:12:08 CST 2014
     */
    public Short getLevel() {
        return level;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column UI_FW_FUNCTION_WIDGET.LEVEL
     *
     * @param level the value for UI_FW_FUNCTION_WIDGET.LEVEL
     *
     * @ibatorgenerated Thu Sep 25 18:12:08 CST 2014
     */
    public void setLevel(Short level) {
        this.level = level;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column UI_FW_FUNCTION_WIDGET.ENABLE_CACHE
     *
     * @return the value of UI_FW_FUNCTION_WIDGET.ENABLE_CACHE
     *
     * @ibatorgenerated Thu Sep 25 18:12:08 CST 2014
     */
    public Integer getEnableCache() {
        return enableCache;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column UI_FW_FUNCTION_WIDGET.ENABLE_CACHE
     *
     * @param enableCache the value for UI_FW_FUNCTION_WIDGET.ENABLE_CACHE
     *
     * @ibatorgenerated Thu Sep 25 18:12:08 CST 2014
     */
    public void setEnableCache(Integer enableCache) {
        this.enableCache = enableCache;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column UI_FW_FUNCTION_WIDGET.PARENT_ID
     *
     * @return the value of UI_FW_FUNCTION_WIDGET.PARENT_ID
     *
     * @ibatorgenerated Thu Sep 25 18:12:08 CST 2014
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column UI_FW_FUNCTION_WIDGET.PARENT_ID
     *
     * @param parentId the value for UI_FW_FUNCTION_WIDGET.PARENT_ID
     *
     * @ibatorgenerated Thu Sep 25 18:12:08 CST 2014
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column UI_FW_FUNCTION_WIDGET.CREATE_TIME
     *
     * @return the value of UI_FW_FUNCTION_WIDGET.CREATE_TIME
     *
     * @ibatorgenerated Thu Sep 25 18:12:08 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column UI_FW_FUNCTION_WIDGET.CREATE_TIME
     *
     * @param createTime the value for UI_FW_FUNCTION_WIDGET.CREATE_TIME
     *
     * @ibatorgenerated Thu Sep 25 18:12:08 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column UI_FW_FUNCTION_WIDGET.UPDATE_TIME
     *
     * @return the value of UI_FW_FUNCTION_WIDGET.UPDATE_TIME
     *
     * @ibatorgenerated Thu Sep 25 18:12:08 CST 2014
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column UI_FW_FUNCTION_WIDGET.UPDATE_TIME
     *
     * @param updateTime the value for UI_FW_FUNCTION_WIDGET.UPDATE_TIME
     *
     * @ibatorgenerated Thu Sep 25 18:12:08 CST 2014
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}