package com.gfan.report.frame.module;

public class UiFwRoleModuleLinkKey {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column UI_FW_ROLE_MODULE_LINK.MODULE_ID
     *
     * @ibatorgenerated Mon May 11 16:32:54 CST 2015
     */
    private Integer moduleId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column UI_FW_ROLE_MODULE_LINK.ROLE_ID
     *
     * @ibatorgenerated Mon May 11 16:32:54 CST 2015
     */
    private Integer roleId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column UI_FW_ROLE_MODULE_LINK.MODULE_ID
     *
     * @return the value of UI_FW_ROLE_MODULE_LINK.MODULE_ID
     *
     * @ibatorgenerated Mon May 11 16:32:54 CST 2015
     */
    public Integer getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column UI_FW_ROLE_MODULE_LINK.MODULE_ID
     *
     * @param moduleId the value for UI_FW_ROLE_MODULE_LINK.MODULE_ID
     *
     * @ibatorgenerated Mon May 11 16:32:54 CST 2015
     */
    public void setModuleId(Integer moduleId) {
        this.moduleId = moduleId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column UI_FW_ROLE_MODULE_LINK.ROLE_ID
     *
     * @return the value of UI_FW_ROLE_MODULE_LINK.ROLE_ID
     *
     * @ibatorgenerated Mon May 11 16:32:54 CST 2015
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column UI_FW_ROLE_MODULE_LINK.ROLE_ID
     *
     * @param roleId the value for UI_FW_ROLE_MODULE_LINK.ROLE_ID
     *
     * @ibatorgenerated Mon May 11 16:32:54 CST 2015
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}