package com.gfan.report.frame.module;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class UserPwdExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table user_pwd
     *
     * @ibatorgenerated Wed Apr 29 15:46:44 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table user_pwd
     *
     * @ibatorgenerated Wed Apr 29 15:46:44 CST 2015
     */
    protected List oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_pwd
     *
     * @ibatorgenerated Wed Apr 29 15:46:44 CST 2015
     */
    public UserPwdExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_pwd
     *
     * @ibatorgenerated Wed Apr 29 15:46:44 CST 2015
     */
    protected UserPwdExample(UserPwdExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_pwd
     *
     * @ibatorgenerated Wed Apr 29 15:46:44 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_pwd
     *
     * @ibatorgenerated Wed Apr 29 15:46:44 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_pwd
     *
     * @ibatorgenerated Wed Apr 29 15:46:44 CST 2015
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_pwd
     *
     * @ibatorgenerated Wed Apr 29 15:46:44 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_pwd
     *
     * @ibatorgenerated Wed Apr 29 15:46:44 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_pwd
     *
     * @ibatorgenerated Wed Apr 29 15:46:44 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_pwd
     *
     * @ibatorgenerated Wed Apr 29 15:46:44 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table user_pwd
     *
     * @ibatorgenerated Wed Apr 29 15:46:44 CST 2015
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return this;
        }

        public Criteria andIdIn(List values) {
            addCriterion("id in", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List values) {
            addCriterion("id not in", values, "id");
            return this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return this;
        }

        public Criteria andUserIdIn(List values) {
            addCriterion("user_id in", values, "userId");
            return this;
        }

        public Criteria andUserIdNotIn(List values) {
            addCriterion("user_id not in", values, "userId");
            return this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return this;
        }

        public Criteria andPwdHashIsNull() {
            addCriterion("pwd_hash is null");
            return this;
        }

        public Criteria andPwdHashIsNotNull() {
            addCriterion("pwd_hash is not null");
            return this;
        }

        public Criteria andPwdHashEqualTo(String value) {
            addCriterion("pwd_hash =", value, "pwdHash");
            return this;
        }

        public Criteria andPwdHashNotEqualTo(String value) {
            addCriterion("pwd_hash <>", value, "pwdHash");
            return this;
        }

        public Criteria andPwdHashGreaterThan(String value) {
            addCriterion("pwd_hash >", value, "pwdHash");
            return this;
        }

        public Criteria andPwdHashGreaterThanOrEqualTo(String value) {
            addCriterion("pwd_hash >=", value, "pwdHash");
            return this;
        }

        public Criteria andPwdHashLessThan(String value) {
            addCriterion("pwd_hash <", value, "pwdHash");
            return this;
        }

        public Criteria andPwdHashLessThanOrEqualTo(String value) {
            addCriterion("pwd_hash <=", value, "pwdHash");
            return this;
        }

        public Criteria andPwdHashLike(String value) {
            addCriterion("pwd_hash like", value, "pwdHash");
            return this;
        }

        public Criteria andPwdHashNotLike(String value) {
            addCriterion("pwd_hash not like", value, "pwdHash");
            return this;
        }

        public Criteria andPwdHashIn(List values) {
            addCriterion("pwd_hash in", values, "pwdHash");
            return this;
        }

        public Criteria andPwdHashNotIn(List values) {
            addCriterion("pwd_hash not in", values, "pwdHash");
            return this;
        }

        public Criteria andPwdHashBetween(String value1, String value2) {
            addCriterion("pwd_hash between", value1, value2, "pwdHash");
            return this;
        }

        public Criteria andPwdHashNotBetween(String value1, String value2) {
            addCriterion("pwd_hash not between", value1, value2, "pwdHash");
            return this;
        }

        public Criteria andPwdSaltIsNull() {
            addCriterion("pwd_salt is null");
            return this;
        }

        public Criteria andPwdSaltIsNotNull() {
            addCriterion("pwd_salt is not null");
            return this;
        }

        public Criteria andPwdSaltEqualTo(String value) {
            addCriterion("pwd_salt =", value, "pwdSalt");
            return this;
        }

        public Criteria andPwdSaltNotEqualTo(String value) {
            addCriterion("pwd_salt <>", value, "pwdSalt");
            return this;
        }

        public Criteria andPwdSaltGreaterThan(String value) {
            addCriterion("pwd_salt >", value, "pwdSalt");
            return this;
        }

        public Criteria andPwdSaltGreaterThanOrEqualTo(String value) {
            addCriterion("pwd_salt >=", value, "pwdSalt");
            return this;
        }

        public Criteria andPwdSaltLessThan(String value) {
            addCriterion("pwd_salt <", value, "pwdSalt");
            return this;
        }

        public Criteria andPwdSaltLessThanOrEqualTo(String value) {
            addCriterion("pwd_salt <=", value, "pwdSalt");
            return this;
        }

        public Criteria andPwdSaltLike(String value) {
            addCriterion("pwd_salt like", value, "pwdSalt");
            return this;
        }

        public Criteria andPwdSaltNotLike(String value) {
            addCriterion("pwd_salt not like", value, "pwdSalt");
            return this;
        }

        public Criteria andPwdSaltIn(List values) {
            addCriterion("pwd_salt in", values, "pwdSalt");
            return this;
        }

        public Criteria andPwdSaltNotIn(List values) {
            addCriterion("pwd_salt not in", values, "pwdSalt");
            return this;
        }

        public Criteria andPwdSaltBetween(String value1, String value2) {
            addCriterion("pwd_salt between", value1, value2, "pwdSalt");
            return this;
        }

        public Criteria andPwdSaltNotBetween(String value1, String value2) {
            addCriterion("pwd_salt not between", value1, value2, "pwdSalt");
            return this;
        }
    }
}