package com.gfan.report.log.dao;

import com.gfan.report.log.module.LogFunctionClick;
import com.gfan.report.log.module.LogFunctionClickExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class LogFunctionClickDAOImpl extends SqlMapClientDaoSupport implements LogFunctionClickDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_FUNCTION_CLICK
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	public LogFunctionClickDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_FUNCTION_CLICK
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	public int countByExample(LogFunctionClickExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"LOG_FUNCTION_CLICK.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_FUNCTION_CLICK
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	public int deleteByExample(LogFunctionClickExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"LOG_FUNCTION_CLICK.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_FUNCTION_CLICK
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	public int deleteByPrimaryKey(Integer id) {
		LogFunctionClick key = new LogFunctionClick();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"LOG_FUNCTION_CLICK.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_FUNCTION_CLICK
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	public void insert(LogFunctionClick record) {
		getSqlMapClientTemplate().insert(
				"LOG_FUNCTION_CLICK.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_FUNCTION_CLICK
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	public void insertSelective(LogFunctionClick record) {
		getSqlMapClientTemplate().insert(
				"LOG_FUNCTION_CLICK.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_FUNCTION_CLICK
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	public List selectByExample(LogFunctionClickExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"LOG_FUNCTION_CLICK.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_FUNCTION_CLICK
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	public LogFunctionClick selectByPrimaryKey(Integer id) {
		LogFunctionClick key = new LogFunctionClick();
		key.setId(id);
		LogFunctionClick record = (LogFunctionClick) getSqlMapClientTemplate()
				.queryForObject(
						"LOG_FUNCTION_CLICK.ibatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_FUNCTION_CLICK
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	public int updateByExampleSelective(LogFunctionClick record,
			LogFunctionClickExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"LOG_FUNCTION_CLICK.ibatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_FUNCTION_CLICK
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	public int updateByExample(LogFunctionClick record,
			LogFunctionClickExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"LOG_FUNCTION_CLICK.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_FUNCTION_CLICK
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	public int updateByPrimaryKeySelective(LogFunctionClick record) {
		int rows = getSqlMapClientTemplate()
				.update("LOG_FUNCTION_CLICK.ibatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_FUNCTION_CLICK
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	public int updateByPrimaryKey(LogFunctionClick record) {
		int rows = getSqlMapClientTemplate()
				.update("LOG_FUNCTION_CLICK.ibatorgenerated_updateByPrimaryKey",
						record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table LOG_FUNCTION_CLICK
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	private static class UpdateByExampleParms extends LogFunctionClickExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				LogFunctionClickExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}