package com.gfan.report.log.dao;

import com.gfan.report.log.module.LogFunctionClick;
import com.gfan.report.log.module.LogFunctionClickExample;
import java.util.List;

public interface LogFunctionClickDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_FUNCTION_CLICK
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	int countByExample(LogFunctionClickExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_FUNCTION_CLICK
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	int deleteByExample(LogFunctionClickExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_FUNCTION_CLICK
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_FUNCTION_CLICK
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	void insert(LogFunctionClick record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_FUNCTION_CLICK
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	void insertSelective(LogFunctionClick record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_FUNCTION_CLICK
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	List selectByExample(LogFunctionClickExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_FUNCTION_CLICK
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	LogFunctionClick selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_FUNCTION_CLICK
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	int updateByExampleSelective(LogFunctionClick record,
                                 LogFunctionClickExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_FUNCTION_CLICK
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	int updateByExample(LogFunctionClick record, LogFunctionClickExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_FUNCTION_CLICK
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	int updateByPrimaryKeySelective(LogFunctionClick record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_FUNCTION_CLICK
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	int updateByPrimaryKey(LogFunctionClick record);
}