package com.gfan.report.log.dao;

import com.gfan.report.log.module.LogSqlQuery;
import com.gfan.report.log.module.LogSqlQueryExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class LogSqlQueryDAOImpl extends SqlMapClientDaoSupport implements LogSqlQueryDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_SQL_QUERY
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	public LogSqlQueryDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_SQL_QUERY
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	public int countByExample(LogSqlQueryExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"LOG_SQL_QUERY.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_SQL_QUERY
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	public int deleteByExample(LogSqlQueryExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"LOG_SQL_QUERY.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_SQL_QUERY
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	public int deleteByPrimaryKey(Integer id) {
		LogSqlQuery key = new LogSqlQuery();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"LOG_SQL_QUERY.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_SQL_QUERY
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	public void insert(LogSqlQuery record) {
		getSqlMapClientTemplate().insert(
				"LOG_SQL_QUERY.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_SQL_QUERY
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	public void insertSelective(LogSqlQuery record) {
		getSqlMapClientTemplate().insert(
				"LOG_SQL_QUERY.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_SQL_QUERY
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	public List selectByExample(LogSqlQueryExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"LOG_SQL_QUERY.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_SQL_QUERY
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	public LogSqlQuery selectByPrimaryKey(Integer id) {
		LogSqlQuery key = new LogSqlQuery();
		key.setId(id);
		LogSqlQuery record = (LogSqlQuery) getSqlMapClientTemplate()
				.queryForObject(
						"LOG_SQL_QUERY.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_SQL_QUERY
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	public int updateByExampleSelective(LogSqlQuery record,
			LogSqlQueryExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update("LOG_SQL_QUERY.ibatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_SQL_QUERY
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	public int updateByExample(LogSqlQuery record, LogSqlQueryExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"LOG_SQL_QUERY.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_SQL_QUERY
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	public int updateByPrimaryKeySelective(LogSqlQuery record) {
		int rows = getSqlMapClientTemplate().update(
				"LOG_SQL_QUERY.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_SQL_QUERY
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	public int updateByPrimaryKey(LogSqlQuery record) {
		int rows = getSqlMapClientTemplate().update(
				"LOG_SQL_QUERY.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table LOG_SQL_QUERY
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	private static class UpdateByExampleParms extends LogSqlQueryExample {
		private Object record;

		public UpdateByExampleParms(Object record, LogSqlQueryExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}