package com.gfan.report.log.dao;

import com.gfan.report.log.module.LogUserLogin;
import com.gfan.report.log.module.LogUserLoginExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class LogUserLoginDAOImpl extends SqlMapClientDaoSupport implements LogUserLoginDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_USER_LOGIN
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	public LogUserLoginDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_USER_LOGIN
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	public int countByExample(LogUserLoginExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"LOG_USER_LOGIN.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_USER_LOGIN
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	public int deleteByExample(LogUserLoginExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"LOG_USER_LOGIN.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_USER_LOGIN
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	public int deleteByPrimaryKey(Integer id) {
		LogUserLogin key = new LogUserLogin();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"LOG_USER_LOGIN.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_USER_LOGIN
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	public void insert(LogUserLogin record) {
		getSqlMapClientTemplate().insert(
				"LOG_USER_LOGIN.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_USER_LOGIN
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	public void insertSelective(LogUserLogin record) {
		getSqlMapClientTemplate().insert(
				"LOG_USER_LOGIN.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_USER_LOGIN
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	public List selectByExample(LogUserLoginExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"LOG_USER_LOGIN.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_USER_LOGIN
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	public LogUserLogin selectByPrimaryKey(Integer id) {
		LogUserLogin key = new LogUserLogin();
		key.setId(id);
		LogUserLogin record = (LogUserLogin) getSqlMapClientTemplate()
				.queryForObject(
						"LOG_USER_LOGIN.ibatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_USER_LOGIN
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	public int updateByExampleSelective(LogUserLogin record,
			LogUserLoginExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"LOG_USER_LOGIN.ibatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_USER_LOGIN
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	public int updateByExample(LogUserLogin record, LogUserLoginExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"LOG_USER_LOGIN.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_USER_LOGIN
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	public int updateByPrimaryKeySelective(LogUserLogin record) {
		int rows = getSqlMapClientTemplate().update(
				"LOG_USER_LOGIN.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_USER_LOGIN
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	public int updateByPrimaryKey(LogUserLogin record) {
		int rows = getSqlMapClientTemplate().update(
				"LOG_USER_LOGIN.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table LOG_USER_LOGIN
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	private static class UpdateByExampleParms extends LogUserLoginExample {
		private Object record;

		public UpdateByExampleParms(Object record, LogUserLoginExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}