package com.gfan.report.log.dao;

import com.gfan.report.log.module.LogUserLogin;
import com.gfan.report.log.module.LogUserLoginExample;
import java.util.List;

public interface LogUserLoginDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_USER_LOGIN
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	int countByExample(LogUserLoginExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_USER_LOGIN
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	int deleteByExample(LogUserLoginExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_USER_LOGIN
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_USER_LOGIN
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	void insert(LogUserLogin record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_USER_LOGIN
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	void insertSelective(LogUserLogin record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_USER_LOGIN
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	List selectByExample(LogUserLoginExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_USER_LOGIN
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	LogUserLogin selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_USER_LOGIN
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	int updateByExampleSelective(LogUserLogin record,
                                 LogUserLoginExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_USER_LOGIN
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	int updateByExample(LogUserLogin record, LogUserLoginExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_USER_LOGIN
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	int updateByPrimaryKeySelective(LogUserLogin record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table LOG_USER_LOGIN
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	int updateByPrimaryKey(LogUserLogin record);
}