package com.gfan.report.frame.dao;

import com.gfan.report.frame.module.CorpPartnerUser;
import com.gfan.report.frame.module.CorpPartnerUserExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class CorpPartnerUserDAOImpl extends SqlMapClientDaoSupport implements CorpPartnerUserDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table corp_partner_user
     *
     * @ibatorgenerated Tue May 12 18:31:37 CST 2015
     */
    public CorpPartnerUserDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table corp_partner_user
     *
     * @ibatorgenerated Tue May 12 18:31:37 CST 2015
     */
    public int countByExample(CorpPartnerUserExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("corp_partner_user.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table corp_partner_user
     *
     * @ibatorgenerated Tue May 12 18:31:37 CST 2015
     */
    public int deleteByExample(CorpPartnerUserExample example) {
        int rows = getSqlMapClientTemplate().delete("corp_partner_user.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table corp_partner_user
     *
     * @ibatorgenerated Tue May 12 18:31:37 CST 2015
     */
    public int deleteByPrimaryKey(Integer id) {
        CorpPartnerUser key = new CorpPartnerUser();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("corp_partner_user.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table corp_partner_user
     *
     * @ibatorgenerated Tue May 12 18:31:37 CST 2015
     */
    public void insert(CorpPartnerUser record) {
        getSqlMapClientTemplate().insert("corp_partner_user.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table corp_partner_user
     *
     * @ibatorgenerated Tue May 12 18:31:37 CST 2015
     */
    public void insertSelective(CorpPartnerUser record) {
        getSqlMapClientTemplate().insert("corp_partner_user.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table corp_partner_user
     *
     * @ibatorgenerated Tue May 12 18:31:37 CST 2015
     */
    public List selectByExample(CorpPartnerUserExample example) {
        List list = getSqlMapClientTemplate().queryForList("corp_partner_user.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table corp_partner_user
     *
     * @ibatorgenerated Tue May 12 18:31:37 CST 2015
     */
    public CorpPartnerUser selectByPrimaryKey(Integer id) {
        CorpPartnerUser key = new CorpPartnerUser();
        key.setId(id);
        CorpPartnerUser record = (CorpPartnerUser) getSqlMapClientTemplate().queryForObject("corp_partner_user.partnerUserId", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table corp_partner_user
     *
     * @ibatorgenerated Tue May 12 18:31:37 CST 2015
     */
    public int updateByExampleSelective(CorpPartnerUser record, CorpPartnerUserExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("corp_partner_user.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table corp_partner_user
     *
     * @ibatorgenerated Tue May 12 18:31:37 CST 2015
     */
    public int updateByExample(CorpPartnerUser record, CorpPartnerUserExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("corp_partner_user.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table corp_partner_user
     *
     * @ibatorgenerated Tue May 12 18:31:37 CST 2015
     */
    public int updateByPrimaryKeySelective(CorpPartnerUser record) {
        int rows = getSqlMapClientTemplate().update("corp_partner_user.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table corp_partner_user
     *
     * @ibatorgenerated Tue May 12 18:31:37 CST 2015
     */
    public int updateByPrimaryKey(CorpPartnerUser record) {
        int rows = getSqlMapClientTemplate().update("corp_partner_user.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table corp_partner_user
     *
     * @ibatorgenerated Tue May 12 18:31:37 CST 2015
     */
    private static class UpdateByExampleParms extends CorpPartnerUserExample {
        private Object record;

        public UpdateByExampleParms(Object record, CorpPartnerUserExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}