package com.gfan.report.frame.dao;

import com.gfan.report.frame.module.PMemberRole;
import com.gfan.report.frame.module.PMemberRoleExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class PMemberRoleDAOImpl extends SqlMapClientDaoSupport implements PMemberRoleDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table p_member_role
     *
     * @ibatorgenerated Wed Apr 29 16:17:26 CST 2015
     */
    public PMemberRoleDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table p_member_role
     *
     * @ibatorgenerated Wed Apr 29 16:17:26 CST 2015
     */
    public int countByExample(PMemberRoleExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("p_member_role.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table p_member_role
     *
     * @ibatorgenerated Wed Apr 29 16:17:26 CST 2015
     */
    public int deleteByExample(PMemberRoleExample example) {
        int rows = getSqlMapClientTemplate().delete("p_member_role.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table p_member_role
     *
     * @ibatorgenerated Wed Apr 29 16:17:26 CST 2015
     */
    public int deleteByPrimaryKey(Integer id) {
        PMemberRole key = new PMemberRole();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("p_member_role.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table p_member_role
     *
     * @ibatorgenerated Wed Apr 29 16:17:26 CST 2015
     */
    public void insert(PMemberRole record) {
        getSqlMapClientTemplate().insert("p_member_role.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table p_member_role
     *
     * @ibatorgenerated Wed Apr 29 16:17:26 CST 2015
     */
    public void insertSelective(PMemberRole record) {
        getSqlMapClientTemplate().insert("p_member_role.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table p_member_role
     *
     * @ibatorgenerated Wed Apr 29 16:17:26 CST 2015
     */
    public List selectByExample(PMemberRoleExample example) {
        List list = getSqlMapClientTemplate().queryForList("p_member_role.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table p_member_role
     *
     * @ibatorgenerated Wed Apr 29 16:17:26 CST 2015
     */
    public PMemberRole selectByPrimaryKey(Integer id) {
        PMemberRole key = new PMemberRole();
        key.setId(id);
        PMemberRole record = (PMemberRole) getSqlMapClientTemplate().queryForObject("p_member_role.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table p_member_role
     *
     * @ibatorgenerated Wed Apr 29 16:17:26 CST 2015
     */
    public int updateByExampleSelective(PMemberRole record, PMemberRoleExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("p_member_role.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table p_member_role
     *
     * @ibatorgenerated Wed Apr 29 16:17:26 CST 2015
     */
    public int updateByExample(PMemberRole record, PMemberRoleExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("p_member_role.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table p_member_role
     *
     * @ibatorgenerated Wed Apr 29 16:17:26 CST 2015
     */
    public int updateByPrimaryKeySelective(PMemberRole record) {
        int rows = getSqlMapClientTemplate().update("p_member_role.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table p_member_role
     *
     * @ibatorgenerated Wed Apr 29 16:17:26 CST 2015
     */
    public int updateByPrimaryKey(PMemberRole record) {
        int rows = getSqlMapClientTemplate().update("p_member_role.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table p_member_role
     *
     * @ibatorgenerated Wed Apr 29 16:17:26 CST 2015
     */
    private static class UpdateByExampleParms extends PMemberRoleExample {
        private Object record;

        public UpdateByExampleParms(Object record, PMemberRoleExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}