package com.gfan.report.frame.dao;

import com.gfan.report.frame.module.RepDict;
import com.gfan.report.frame.module.RepDictExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class RepDictDAOImpl extends SqlMapClientDaoSupport implements RepDictDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table REP_DICT
     *
     * @ibatorgenerated Fri Sep 26 16:42:48 CST 2014
     */
    public RepDictDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table REP_DICT
     *
     * @ibatorgenerated Fri Sep 26 16:42:48 CST 2014
     */
    public int countByExample(RepDictExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("REP_DICT.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table REP_DICT
     *
     * @ibatorgenerated Fri Sep 26 16:42:48 CST 2014
     */
    public int deleteByExample(RepDictExample example) {
        int rows = getSqlMapClientTemplate().delete("REP_DICT.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table REP_DICT
     *
     * @ibatorgenerated Fri Sep 26 16:42:48 CST 2014
     */
    public int deleteByPrimaryKey(Integer id) {
        RepDict key = new RepDict();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("REP_DICT.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table REP_DICT
     *
     * @ibatorgenerated Fri Sep 26 16:42:48 CST 2014
     */
    public void insert(RepDict record) {
        getSqlMapClientTemplate().insert("REP_DICT.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table REP_DICT
     *
     * @ibatorgenerated Fri Sep 26 16:42:48 CST 2014
     */
    public void insertSelective(RepDict record) {
        getSqlMapClientTemplate().insert("REP_DICT.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table REP_DICT
     *
     * @ibatorgenerated Fri Sep 26 16:42:48 CST 2014
     */
    public List selectByExample(RepDictExample example) {
        List list = getSqlMapClientTemplate().queryForList("REP_DICT.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table REP_DICT
     *
     * @ibatorgenerated Fri Sep 26 16:42:48 CST 2014
     */
    public RepDict selectByPrimaryKey(Integer id) {
        RepDict key = new RepDict();
        key.setId(id);
        RepDict record = (RepDict) getSqlMapClientTemplate().queryForObject("REP_DICT.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table REP_DICT
     *
     * @ibatorgenerated Fri Sep 26 16:42:48 CST 2014
     */
    public int updateByExampleSelective(RepDict record, RepDictExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("REP_DICT.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table REP_DICT
     *
     * @ibatorgenerated Fri Sep 26 16:42:48 CST 2014
     */
    public int updateByExample(RepDict record, RepDictExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("REP_DICT.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table REP_DICT
     *
     * @ibatorgenerated Fri Sep 26 16:42:48 CST 2014
     */
    public int updateByPrimaryKeySelective(RepDict record) {
        int rows = getSqlMapClientTemplate().update("REP_DICT.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table REP_DICT
     *
     * @ibatorgenerated Fri Sep 26 16:42:48 CST 2014
     */
    public int updateByPrimaryKey(RepDict record) {
        int rows = getSqlMapClientTemplate().update("REP_DICT.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table REP_DICT
     *
     * @ibatorgenerated Fri Sep 26 16:42:48 CST 2014
     */
    private static class UpdateByExampleParms extends RepDictExample {
        private Object record;

        public UpdateByExampleParms(Object record, RepDictExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}