package com.gfan.report.frame.dao;

import com.gfan.report.frame.module.RepDict;
import com.gfan.report.frame.module.RepDictExample;
import java.util.List;

public interface RepDictDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table REP_DICT
     *
     * @ibatorgenerated Fri Sep 26 16:42:48 CST 2014
     */
    int countByExample(RepDictExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table REP_DICT
     *
     * @ibatorgenerated Fri Sep 26 16:42:48 CST 2014
     */
    int deleteByExample(RepDictExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table REP_DICT
     *
     * @ibatorgenerated Fri Sep 26 16:42:48 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table REP_DICT
     *
     * @ibatorgenerated Fri Sep 26 16:42:48 CST 2014
     */
    void insert(RepDict record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table REP_DICT
     *
     * @ibatorgenerated Fri Sep 26 16:42:48 CST 2014
     */
    void insertSelective(RepDict record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table REP_DICT
     *
     * @ibatorgenerated Fri Sep 26 16:42:48 CST 2014
     */
    List selectByExample(RepDictExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table REP_DICT
     *
     * @ibatorgenerated Fri Sep 26 16:42:48 CST 2014
     */
    RepDict selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table REP_DICT
     *
     * @ibatorgenerated Fri Sep 26 16:42:48 CST 2014
     */
    int updateByExampleSelective(RepDict record, RepDictExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table REP_DICT
     *
     * @ibatorgenerated Fri Sep 26 16:42:48 CST 2014
     */
    int updateByExample(RepDict record, RepDictExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table REP_DICT
     *
     * @ibatorgenerated Fri Sep 26 16:42:48 CST 2014
     */
    int updateByPrimaryKeySelective(RepDict record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table REP_DICT
     *
     * @ibatorgenerated Fri Sep 26 16:42:48 CST 2014
     */
    int updateByPrimaryKey(RepDict record);
}