package com.gfan.report.frame.dao;

import java.util.List;

import com.gfan.report.frame.module.RepQuery;
import com.gfan.report.frame.module.RepQueryExample;
import java.sql.SQLException;

public interface RepQueryDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table rep_query
	 * @ibatorgenerated  Thu Dec 04 17:40:07 CST 2014
	 */
	int countByExample(RepQueryExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table rep_query
	 * @ibatorgenerated  Thu Dec 04 17:40:07 CST 2014
	 */
	int deleteByExample(RepQueryExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table rep_query
	 * @ibatorgenerated  Thu Dec 04 17:40:07 CST 2014
	 */
	int deleteByPrimaryKey(String reportName);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table rep_query
	 * @ibatorgenerated  Thu Dec 04 17:40:07 CST 2014
	 */
	void insert(RepQuery record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table rep_query
	 * @ibatorgenerated  Thu Dec 04 17:40:07 CST 2014
	 */
	void insertSelective(RepQuery record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table rep_query
	 * @ibatorgenerated  Thu Dec 04 17:40:07 CST 2014
	 */
	List<RepQuery> selectByExample(RepQueryExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table rep_query
	 * @ibatorgenerated  Thu Dec 04 17:40:07 CST 2014
	 */
	RepQuery selectByPrimaryKey(String reportName);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table rep_query
	 * @ibatorgenerated  Thu Dec 04 17:40:07 CST 2014
	 */
	int updateByExampleSelective(RepQuery record, RepQueryExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table rep_query
	 * @ibatorgenerated  Thu Dec 04 17:40:07 CST 2014
	 */
	int updateByExample(RepQuery record, RepQueryExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table rep_query
	 * @ibatorgenerated  Thu Dec 04 17:40:07 CST 2014
	 */
	int updateByPrimaryKeySelective(RepQuery record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table rep_query
	 * @ibatorgenerated  Thu Dec 04 17:40:07 CST 2014
	 */
	int updateByPrimaryKey(RepQuery record);
}