package com.gfan.report.frame.dao;

import com.gfan.report.frame.module.UiFwRoleFunctionLinkExample;
import com.gfan.report.frame.module.UiFwRoleFunctionLinkKey;
import java.util.List;

public interface UiFwRoleFunctionLinkDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_ROLE_FUNCTION_LINK
     *
     * @ibatorgenerated Mon May 11 16:32:54 CST 2015
     */
    int countByExample(UiFwRoleFunctionLinkExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_ROLE_FUNCTION_LINK
     *
     * @ibatorgenerated Mon May 11 16:32:54 CST 2015
     */
    int deleteByExample(UiFwRoleFunctionLinkExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_ROLE_FUNCTION_LINK
     *
     * @ibatorgenerated Mon May 11 16:32:54 CST 2015
     */
    int deleteByPrimaryKey(UiFwRoleFunctionLinkKey key);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_ROLE_FUNCTION_LINK
     *
     * @ibatorgenerated Mon May 11 16:32:54 CST 2015
     */
    void insert(UiFwRoleFunctionLinkKey record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_ROLE_FUNCTION_LINK
     *
     * @ibatorgenerated Mon May 11 16:32:54 CST 2015
     */
    void insertSelective(UiFwRoleFunctionLinkKey record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_ROLE_FUNCTION_LINK
     *
     * @ibatorgenerated Mon May 11 16:32:54 CST 2015
     */
    List selectByExample(UiFwRoleFunctionLinkExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_ROLE_FUNCTION_LINK
     *
     * @ibatorgenerated Mon May 11 16:32:54 CST 2015
     */
    int updateByExampleSelective(UiFwRoleFunctionLinkKey record, UiFwRoleFunctionLinkExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_ROLE_FUNCTION_LINK
     *
     * @ibatorgenerated Mon May 11 16:32:54 CST 2015
     */
    int updateByExample(UiFwRoleFunctionLinkKey record, UiFwRoleFunctionLinkExample example);
}