package com.gfan.report.frame.dao;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.gfan.report.frame.module.UiFwFunction;
import com.gfan.report.frame.module.UiFwFunctionExample;

public class UiFwFunctionDAOImpl extends SqlMapClientDaoSupport implements UiFwFunctionDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_FUNCTION
     *
     * @ibatorgenerated Thu Sep 25 15:11:46 CST 2014
     */
    public UiFwFunctionDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_FUNCTION
     *
     * @ibatorgenerated Thu Sep 25 15:11:46 CST 2014
     */
    public int countByExample(UiFwFunctionExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("UI_FW_FUNCTION.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_FUNCTION
     *
     * @ibatorgenerated Thu Sep 25 15:11:46 CST 2014
     */
    public int deleteByExample(UiFwFunctionExample example) {
        int rows = getSqlMapClientTemplate().delete("UI_FW_FUNCTION.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_FUNCTION
     *
     * @ibatorgenerated Thu Sep 25 15:11:46 CST 2014
     */
    public int deleteByPrimaryKey(Integer id) {
        UiFwFunction key = new UiFwFunction();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("UI_FW_FUNCTION.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_FUNCTION
     *
     * @ibatorgenerated Thu Sep 25 15:11:46 CST 2014
     */
    public void insert(UiFwFunction record) {
        getSqlMapClientTemplate().insert("UI_FW_FUNCTION.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_FUNCTION
     *
     * @ibatorgenerated Thu Sep 25 15:11:46 CST 2014
     */
    public void insertSelective(UiFwFunction record) {
        getSqlMapClientTemplate().insert("UI_FW_FUNCTION.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_FUNCTION
     *
     * @ibatorgenerated Thu Sep 25 15:11:46 CST 2014
     */
    public List selectByExample(UiFwFunctionExample example) {
        List list = getSqlMapClientTemplate().queryForList("UI_FW_FUNCTION.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_FUNCTION
     *
     * @ibatorgenerated Thu Sep 25 15:11:46 CST 2014
     */
    public UiFwFunction selectByPrimaryKey(Integer id) {
        UiFwFunction key = new UiFwFunction();
        key.setId(id);
        UiFwFunction record = (UiFwFunction) getSqlMapClientTemplate().queryForObject("UI_FW_FUNCTION.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_FUNCTION
     *
     * @ibatorgenerated Thu Sep 25 15:11:46 CST 2014
     */
    public int updateByExampleSelective(UiFwFunction record, UiFwFunctionExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("UI_FW_FUNCTION.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_FUNCTION
     *
     * @ibatorgenerated Thu Sep 25 15:11:46 CST 2014
     */
    public int updateByExample(UiFwFunction record, UiFwFunctionExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("UI_FW_FUNCTION.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_FUNCTION
     *
     * @ibatorgenerated Thu Sep 25 15:11:46 CST 2014
     */
    public int updateByPrimaryKeySelective(UiFwFunction record) {
        int rows = getSqlMapClientTemplate().update("UI_FW_FUNCTION.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_FUNCTION
     *
     * @ibatorgenerated Thu Sep 25 15:11:46 CST 2014
     */
    public int updateByPrimaryKey(UiFwFunction record) {
        int rows = getSqlMapClientTemplate().update("UI_FW_FUNCTION.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table UI_FW_FUNCTION
     *
     * @ibatorgenerated Thu Sep 25 15:11:46 CST 2014
     */
    private static class UpdateByExampleParms extends UiFwFunctionExample {
        private Object record;

        public UpdateByExampleParms(Object record, UiFwFunctionExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

	@Override
	public List selectByUserId(Integer userId) {
		UiFwFunction key = new UiFwFunction();
        key.setId(userId);
        List list = getSqlMapClientTemplate().queryForList("UI_FW_FUNCTION.ibatorgenerated_selectByUserId", key);
        return list;
	}
}