package com.gfan.report.frame.dao;

import com.gfan.report.frame.module.UiFwRoleModuleLinkExample;
import com.gfan.report.frame.module.UiFwRoleModuleLinkKey;
import java.util.List;

public interface UiFwRoleModuleLinkDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_ROLE_MODULE_LINK
     *
     * @ibatorgenerated Mon May 11 16:32:54 CST 2015
     */
    int countByExample(UiFwRoleModuleLinkExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_ROLE_MODULE_LINK
     *
     * @ibatorgenerated Mon May 11 16:32:54 CST 2015
     */
    int deleteByExample(UiFwRoleModuleLinkExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_ROLE_MODULE_LINK
     *
     * @ibatorgenerated Mon May 11 16:32:54 CST 2015
     */
    int deleteByPrimaryKey(UiFwRoleModuleLinkKey key);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_ROLE_MODULE_LINK
     *
     * @ibatorgenerated Mon May 11 16:32:54 CST 2015
     */
    void insert(UiFwRoleModuleLinkKey record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_ROLE_MODULE_LINK
     *
     * @ibatorgenerated Mon May 11 16:32:54 CST 2015
     */
    void insertSelective(UiFwRoleModuleLinkKey record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_ROLE_MODULE_LINK
     *
     * @ibatorgenerated Mon May 11 16:32:54 CST 2015
     */
    List selectByExample(UiFwRoleModuleLinkExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_ROLE_MODULE_LINK
     *
     * @ibatorgenerated Mon May 11 16:32:54 CST 2015
     */
    int updateByExampleSelective(UiFwRoleModuleLinkKey record, UiFwRoleModuleLinkExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table UI_FW_ROLE_MODULE_LINK
     *
     * @ibatorgenerated Mon May 11 16:32:54 CST 2015
     */
    int updateByExample(UiFwRoleModuleLinkKey record, UiFwRoleModuleLinkExample example);
}