package com.gfan.report.frame.dao;

import com.gfan.report.frame.module.UserPwd;
import com.gfan.report.frame.module.UserPwdExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class UserPwdDAOImpl extends SqlMapClientDaoSupport implements UserPwdDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_pwd
     *
     * @ibatorgenerated Wed Apr 29 15:46:44 CST 2015
     */
    public UserPwdDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_pwd
     *
     * @ibatorgenerated Wed Apr 29 15:46:44 CST 2015
     */
    public int countByExample(UserPwdExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("user_pwd.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_pwd
     *
     * @ibatorgenerated Wed Apr 29 15:46:44 CST 2015
     */
    public int deleteByExample(UserPwdExample example) {
        int rows = getSqlMapClientTemplate().delete("user_pwd.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_pwd
     *
     * @ibatorgenerated Wed Apr 29 15:46:44 CST 2015
     */
    public int deleteByPrimaryKey(Integer id) {
        UserPwd key = new UserPwd();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("user_pwd.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_pwd
     *
     * @ibatorgenerated Wed Apr 29 15:46:44 CST 2015
     */
    public void insert(UserPwd record) {
        getSqlMapClientTemplate().insert("user_pwd.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_pwd
     *
     * @ibatorgenerated Wed Apr 29 15:46:44 CST 2015
     */
    public void insertSelective(UserPwd record) {
        getSqlMapClientTemplate().insert("user_pwd.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_pwd
     *
     * @ibatorgenerated Wed Apr 29 15:46:44 CST 2015
     */
    public List selectByExample(UserPwdExample example) {
        List list = getSqlMapClientTemplate().queryForList("user_pwd.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_pwd
     *
     * @ibatorgenerated Wed Apr 29 15:46:44 CST 2015
     */
    public UserPwd selectByPrimaryKey(Integer id) {
        UserPwd key = new UserPwd();
        key.setId(id);
        UserPwd record = (UserPwd) getSqlMapClientTemplate().queryForObject("user_pwd.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_pwd
     *
     * @ibatorgenerated Wed Apr 29 15:46:44 CST 2015
     */
    public int updateByExampleSelective(UserPwd record, UserPwdExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("user_pwd.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_pwd
     *
     * @ibatorgenerated Wed Apr 29 15:46:44 CST 2015
     */
    public int updateByExample(UserPwd record, UserPwdExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("user_pwd.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_pwd
     *
     * @ibatorgenerated Wed Apr 29 15:46:44 CST 2015
     */
    public int updateByPrimaryKeySelective(UserPwd record) {
        int rows = getSqlMapClientTemplate().update("user_pwd.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_pwd
     *
     * @ibatorgenerated Wed Apr 29 15:46:44 CST 2015
     */
    public int updateByPrimaryKey(UserPwd record) {
        int rows = getSqlMapClientTemplate().update("user_pwd.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table user_pwd
     *
     * @ibatorgenerated Wed Apr 29 15:46:44 CST 2015
     */
    private static class UpdateByExampleParms extends UserPwdExample {
        private Object record;

        public UpdateByExampleParms(Object record, UserPwdExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}