package com.gfan.report.log.module;

import java.util.Date;

public class LogFunctionClick {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column LOG_FUNCTION_CLICK.ID
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column LOG_FUNCTION_CLICK.USER_ID
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	private String userId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column LOG_FUNCTION_CLICK.USER_NAME
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	private String userName;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column LOG_FUNCTION_CLICK.USER_IP
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	private String userIp;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column LOG_FUNCTION_CLICK.FUNCTION_ID
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	private Integer functionId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column LOG_FUNCTION_CLICK.FUNCTION_NAME
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	private String functionName;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column LOG_FUNCTION_CLICK.LOG_TIME
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	private Date logTime;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column LOG_FUNCTION_CLICK.INSERT_TIME
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	private Date insertTime;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column LOG_FUNCTION_CLICK.ID
	 * @return  the value of LOG_FUNCTION_CLICK.ID
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column LOG_FUNCTION_CLICK.ID
	 * @param id  the value for LOG_FUNCTION_CLICK.ID
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column LOG_FUNCTION_CLICK.USER_ID
	 * @return  the value of LOG_FUNCTION_CLICK.USER_ID
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column LOG_FUNCTION_CLICK.USER_ID
	 * @param userId  the value for LOG_FUNCTION_CLICK.USER_ID
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column LOG_FUNCTION_CLICK.USER_NAME
	 * @return  the value of LOG_FUNCTION_CLICK.USER_NAME
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column LOG_FUNCTION_CLICK.USER_NAME
	 * @param userName  the value for LOG_FUNCTION_CLICK.USER_NAME
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column LOG_FUNCTION_CLICK.USER_IP
	 * @return  the value of LOG_FUNCTION_CLICK.USER_IP
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	public String getUserIp() {
		return userIp;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column LOG_FUNCTION_CLICK.USER_IP
	 * @param userIp  the value for LOG_FUNCTION_CLICK.USER_IP
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	public void setUserIp(String userIp) {
		this.userIp = userIp;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column LOG_FUNCTION_CLICK.FUNCTION_ID
	 * @return  the value of LOG_FUNCTION_CLICK.FUNCTION_ID
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	public Integer getFunctionId() {
		return functionId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column LOG_FUNCTION_CLICK.FUNCTION_ID
	 * @param functionId  the value for LOG_FUNCTION_CLICK.FUNCTION_ID
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	public void setFunctionId(Integer functionId) {
		this.functionId = functionId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column LOG_FUNCTION_CLICK.FUNCTION_NAME
	 * @return  the value of LOG_FUNCTION_CLICK.FUNCTION_NAME
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	public String getFunctionName() {
		return functionName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column LOG_FUNCTION_CLICK.FUNCTION_NAME
	 * @param functionName  the value for LOG_FUNCTION_CLICK.FUNCTION_NAME
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	public void setFunctionName(String functionName) {
		this.functionName = functionName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column LOG_FUNCTION_CLICK.LOG_TIME
	 * @return  the value of LOG_FUNCTION_CLICK.LOG_TIME
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	public Date getLogTime() {
		return logTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column LOG_FUNCTION_CLICK.LOG_TIME
	 * @param logTime  the value for LOG_FUNCTION_CLICK.LOG_TIME
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	public void setLogTime(Date logTime) {
		this.logTime = logTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column LOG_FUNCTION_CLICK.INSERT_TIME
	 * @return  the value of LOG_FUNCTION_CLICK.INSERT_TIME
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	public Date getInsertTime() {
		return insertTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column LOG_FUNCTION_CLICK.INSERT_TIME
	 * @param insertTime  the value for LOG_FUNCTION_CLICK.INSERT_TIME
	 * @ibatorgenerated  Mon Dec 08 17:42:40 CST 2014
	 */
	public void setInsertTime(Date insertTime) {
		this.insertTime = insertTime;
	}
}